# Generated by Django 2.2.28 on 2026-04-19 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Raza')),
                ('description', models.TextField(help_text='Descripción general de la raza', verbose_name='Descripción')),
                ('characteristics', models.TextField(blank=True, help_text='Características principales de la raza', verbose_name='Características')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('description', models.TextField(help_text='Información sobre salud, historial genético y cualidades de reproducción', verbose_name='Descripción de Salud/Genética')),
                ('image', models.ImageField(help_text='Foto del animal', upload_to='pets/', verbose_name='Foto')),
                ('health_certificate', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificado de Salud')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible para cruza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.Breeds', verbose_name='Raza')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-created_at'],
            },
        ),
    ]
